import { Public_Sans } from "next/font/google";
import "./globals.css";

const public_Sans = Public_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={public_Sans.className}>{children}</body>
    </html>
  );
}
